### ISSUE TITLE
/rinfo 指令报错

### ISSUE THREAD

**Issue by Vjjvj** [Shadow403/nonebot_plugin_lolinfo#1]
10-06 12:43:01 [SUCCESS] nonebot | OneBot V11 3553757724 | [message.private.friend]: Message qq from qq '/rinfo 塞拉斯'
10-06 12:43:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_lolinfo.controllers.ctroll_rinfo, lineno=11)
10-06 12:43:01 [INFO] nonebot_plugin_lolinfo | 开始获取数据 https://api-dev.shadow403.cn/api/lol/heroRank/塞拉斯?posi=
10-06 12:43:10 [SUCCESS] nonebot_plugin_lolinfo | 获取数据成功 https://api-dev.shadow403.cn/api/lol/heroRank/塞拉斯?posi=
10-06 12:43:10 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_lolinfo.controllers.ctroll_rinfo, lineno=11) running complete
10-06 12:43:10 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_lolinfo.controllers.ctroll_rinfo, lineno=11) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\vvv\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\vvv\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\vvv\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "E:\vvv\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "F:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "E:\vvv\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\vvv\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\vvv\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\vvv\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\vvv\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\vvv\.venv\Lib\site-packages\nonebot_plugin_lolinfo\controllers\ctroll_rinfo.py", line 27, in heroRank_handle
    rImg = await _d_rinfo(rDict)
  File "E:\vvv\.venv\Lib\site-packages\nonebot_plugin_lolinfo\draw\draw_rinfo.py", line 8, in _d_rinfo
    rUrl = Func_parseDict(rDict)
  File "E:\vvv\.venv\Lib\site-packages\nonebot_plugin_lolinfo\utils\util_urlpath.py", line 61, in Func_parseDict
    _CE_Boots = _f_parse_item(_CE_["R_EQUIP"]["BOOTS_EQUIP"])
  File "E:\vvv\.venv\Lib\site-packages\nonebot_plugin_lolinfo\utils\util_urlpath.py", line 11, in _f_parse_item
    _v1 = f"{PluginConfig.html_str}{PluginConfig.img_url}/{_v0}{PluginConfig.img_minetype}{PluginConfig.html_end}"
  File "E:\vvv\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 262, in __getattr__
    raise AttributeError(item)
AttributeError: html_str

/hinfo可以正常发送消息

**Comment by Shadow403** [comment]
Fixed On https://github.com/Shadow403/nonebot_plugin_lolinfo/commit/378c4c2c198183e0ce405c73cad293118f0c9ef5
