### ISSUE TITLE
[Bug]插件无法正常启动

### ISSUE THREAD

**Issue by Jerry-Z07** [Shadow403/nonebot_plugin_lolinfo#2]
ubuntu 22.04
py 3.10
nb 2.3.3
报错信息如下

```
[ERROR] nonebot | Failed to import "nonebot_plugin_lolinfo"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot_plugin_lolinfo/__init__.py", line 2, in <module>
    from .controllers import *
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot_plugin_lolinfo/controllers/__init__.py", line 1, in <module>
    from .ctroll_hinfo import ImgHeroInfo
  File "/home/lxm/桌面/Bot/nb-game/nb-game/.venv/lib/python3.10/site-packages/nonebot_plugin_lolinfo/controllers/ctroll_hinfo.py", line 31
    await ImgHeroInfo.finish(MessageSegment.text(f"返回状态码 {rDict["code"]}\n信息: {rDict["message"]}"))
                                                                           ^^^^
SyntaxError: f-string: unmatched '['

```

**Comment by lin6953** [comment]
遇到了同样的问题

**Comment by Shadow403** [comment]
并未在 `windows` 系统上复现，似乎是字符导致的问题
1. 可以尝试将 `\n`删除后试试
2. 将 `f"返回状态码 {rDict["code"]}\n信息: {rDict["message"]}"` 改为 `"返回状态码 {}\n信息: {}".format(rDict["code"], {rDict["message"])` 使用 `format() 函数`

**Comment by lin6953** [comment]
> 并未在 `windows` 系统上复现，似乎是字符导致的问题
> 1. 可以尝试将 `\n`删除后试试
> 2. 将 `f"返回状态码 {rDict["code"]}\n信息: {rDict["message"]}"` 改为 `"返回状态码 {}\n信息: {}".format(rDict["code"], {rDict["message"])` 使用 `format() 函数`

按照更改后依旧出现启动报错
![Image_1728828026953.png](https://github.com/user-attachments/assets/38ff52f6-5bb5-4f62-81fc-25d5ddae11a0)

这是更改后的源码![Image_1728828029688.png](https://github.com/user-attachments/assets/e5d5951d-9322-4a9e-bf1a-f6114d50312a)

**Comment by Well2333** [comment]
https://github.com/Shadow403/nonebot_plugin_lolinfo/blob/master/nonebot_plugin_lolinfo/controllers/ctroll_hinfo.py#L31

```await ImgHeroInfo.finish(MessageSegment.text(f"返回状态码 {rDict["code"]}\n信息: {rDict["message"]}"))```

代码同时在文本本身和 f-string 中使用了`"`（双引号），这会导致解析器错误，也就是图中的报错，请将其改为

```await ImgHeroInfo.finish(MessageSegment.text(f"返回状态码 {rDict['code']}\n信息: {rDict['message']}"))```

即可

**Comment by Well2333** [comment]
https://github.com/Shadow403/nonebot_plugin_lolinfo/blob/master/nonebot_plugin_lolinfo/draw/draw_hinfo.py#L7-L79

同理，这个模块中也存在此类问题，建议作者将全部模块逐一排查，防止双引号的重复嵌套

**Comment by Shadow403** [comment]
应该在 https://github.com/Shadow403/nonebot_plugin_lolinfo/commit/c56f9ba32d5a6fbba69d664c7ee8cf1f15894f5e 修复了 😎
