### ISSUE TITLE
加载报错：f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by Itachi828** [Shadow403/nonebot_plugin_lolinfo#4]
10-30 12:22:57 [ERROR] nonebot | Failed to import "nonebot_plugin_lolinfo"
Traceback (most recent call last):
  File "/opt/itachi/zhenxun_bot/bot.py", line 24, in <module>
    nonebot.load_plugins("zhenxun/plugins")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-PT62SJIo-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-PT62SJIo-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-PT62SJIo-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-PT62SJIo-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-PT62SJIo-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/itachi/zhenxun_bot/zhenxun/plugins/nonebot_plugin_lolinfo/__init__.py", line 2, in <module>
    from .controllers import *
  File "/opt/itachi/zhenxun_bot/zhenxun/plugins/nonebot_plugin_lolinfo/controllers/__init__.py", line 1, in <module>
    from .ctroll_hinfo import ImgHeroInfo
  File "/opt/itachi/zhenxun_bot/zhenxun/plugins/nonebot_plugin_lolinfo/controllers/ctroll_hinfo.py", line 6, in <module>
    from ..draw.draw_hinfo import _d_hinfo
  File "/opt/itachi/zhenxun_bot/zhenxun/plugins/nonebot_plugin_lolinfo/draw/draw_hinfo.py", line 79
    """
       ^
SyntaxError: f-string expression part cannot include a backslash
python版本：3.10.9

**Comment by Shadow403** [comment]
fixed https://github.com/Shadow403/nonebot_plugin_lolinfo/commit/2d602803055fdf6705971ab15817edb22d3a65a6
